# Basic
max_width = 100
use_small_heuristics = "Max"
# Imports
imports_granularity = "Crate"
reorder_imports = true
# Consistency
newline_style = "Unix"
# Format comments
# comment_width = 100
# wrap_comments = false
# Misc
chain_width = 80
binop_separator = "Back"
match_arm_blocks = false
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
use_field_init_shorthand = true
trailing_semicolon = false
edition = "2021"
